name: merge-job

on:
  pull_request:
    types: [closed, edited]

jobs:
  merge-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Increment Version if same as Master
      id: version
      run: |
        DIFF=$(git diff origin/$GITHUB_HEAD_REF origin/master  -- VERSION)
        if [[ -z "$DIFF" ]]; then
          IFS='.'; read -r -a array <<< "$(cat VERSION)"
          CNT="${array[1]}"
          ((CNT++))
          echo "${array[0]}.${CNT}.${array[2]}" >VERSION
          echo ::set-output name=version::1
        fi

    - name: Print version value   
      run:
        echo steps.id.version.version

    - name: Commit Updated Version File
      if: steps.id.version.version == 1
      run: |
        git add VERSION
        git commit -m "Updated the VERSION file
  
    - name: Push changes to master
      if: steps.id.version.version == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true

    - name: PING - Dispatch initiating repository event
      run: |
        curl -X POST https://api.github.com/repos/erikdeirdre/test_repo_2/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Content-Type: application/json' \
        -u ${{ secrets.ACCESS_TOKEN }} \
        --data '{"event_type": "version_change", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
