name: merge-job

on:
  pull_request:
    types: [closed, edited]

jobs:
  merge-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Find the values
      run: |
        echo "Git Ref: $GITHUB_REF"
        echo "Workspace: $GITHUB_WORKSPACE"
        echo "Event Name: $GITHUB_EVENT_NAME"
        echo "Owner: $GITHUB_REPOSITORY_OWNER"
        echo "Repo: $GITHUB_REPOSITORY"
#    - name: PING - Dispatch initiating repository event
#      run: |
#        curl -X POST https://api.github.com/repos/marcnuri-demo/actions-remote-dispatch-b/dispatches \
#        -H 'Accept: application/vnd.github.everest-preview+json' \
#        -u ${{ secrets.ACCESS_TOKEN }} \
#        --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}
