name: push-job

on:
  push:

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git history
      run: |
        git diff $GITHUB_HEAD_REF origin/master -- VERSION
        
    - name: Increment Version if same as Master
      id: version
      env:
        VER: "$(cat VERSION)"
      run: |
        echo ::set-env name=VERSION::$VER
        echo "TAG: ${{ env.VERSION }}"
        echo "TAG2: ${{ env.VER }}"

    - name: Increment Version
      run: |
        echo "VER: ${{ env.VER }}"
        echo "VERSION: ${{ env.VERSION }}"