name: push-job

on:
  push:

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git history
      run: |
        git diff $GITHUB_HEAD_REF origin/master -- VERSION
        
    - name: Increment Version if same as Master
      id: version
      env:
        VERSION: "$(cat VERSION)"
      run: |
        cat VERSION
        VER=$(cat VERSION)
        echo "VER: ${VER}"
        echo "TAG: ${{ env.VERSION }}"
        echo "TAG2: ${VERSION}"